name: Rust

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
# Tests cant run this branch
# Read TESTING.md for more info
